import { z } from "zod";

export const saveBrochureSchema = z.object({
  originalFileName: z.string().min(1),
  fileSizeMB: z.string().min(1),
  pageCount: z.number().int().positive(),
  rawTextLength: z.number().int().nonnegative(),
  projectName: z.string().max(100).optional(),
  developerName: z.string().max(100).optional(),
  reraNumber: z.string().max(100).optional(),
  projectWebsite: z.string().url().or(z.string().max(255).optional()).optional(),
  contactNumber: z.string().max(30).optional(),
  city: z.string().max(100).optional(),
  area: z.string().max(100).optional(),
  state: z.string().max(100).optional(),
  landmark: z.string().max(255).optional(),
  fullAddress: z.string().max(500).optional(),
  propertyTypes: z.array(z.string()).optional(),
  configurations: z.array(z.string()).optional(),
  totalUnits: z.number().int().positive().optional(),
  totalTowers: z.number().int().positive().optional(),
  totalFloors: z.number().int().positive().optional(),
  sizeMin: z.number().positive().optional(),
  sizeMax: z.number().positive().optional(),
  sizeUnit: z.string().max(20).optional(),
  startingPrice: z.number().positive().optional(),
  maxPrice: z.number().positive().optional(),
  pricePerSqft: z.number().positive().optional(),
  priceLabel: z.string().max(100).optional(),
  paymentPlan: z.string().max(500).optional(),
  bankApprovals: z.array(z.string()).optional(),
  maintenanceCharge: z.string().max(100).optional(),
  possessionDate: z.string().max(100).optional(),
  launchDate: z.string().max(100).optional(),
  constructionStatus: z.string().max(100).optional(),
  amenities: z.array(z.string()).optional(),
  specifications: z.array(z.string()).optional(),
  nearbyInfrastructure: z.array(z.string()).optional(),
  usps: z.array(z.string()).optional(),
  minimumBudget: z.number().positive().optional(),
  maximumBudget: z.number().positive().optional(),
  targetBuyerProfile: z.string().max(500).optional(),
  preferredLocations: z.array(z.string()).optional(),
  investmentType: z.array(z.string()).optional(),
  keyQualifyingQuestions: z.array(z.string()).optional(),
  confidence: z.number().min(0).max(1).optional(),
  extractionWarnings: z.array(z.string()).optional(),
});

export const updateBrochureSchema = saveBrochureSchema.partial();

export type SaveBrochureBody = z.infer<typeof saveBrochureSchema>;
export type UpdateBrochureBody = z.infer<typeof updateBrochureSchema>;